<div id="head">
    <div class="left">
        <a href="#" class="logo"><img src="/img/admin/logo.png" alt=""></a>
        <a href="#" class="button profile"><img src="/img/admin/icons/top/huser.png" alt="" /></a>
        <?php echo $this->loggedUser() ?>
    </div>
    <div class="right">
        <form action="#" id="search" class="search placeholder">
            <label>Looking for something ?</label>
            <input type="text" value="" name="q" class="text"/>
            <input type="submit" value="rechercher" class="submit"/>
        </form>
    </div>
</div>