<div id="sidebar">
            <ul>
                <li>
                    <a href="index.php">
                        <img src="/adminimg/icons/menu/inbox.png" alt="" />
                        <?php echo $this->title ?>
                    </a>
                </li>
                <li class="current hover"><a href="#"><img src="/adminimg/icons/menu/layout.png" alt="" /> Elements</a>
                    <ul>
                        <li><a href="index.html">Dashboard</a></li>
                        <li><a href="forms.html">Forms</a></li>
                        <li class="current"><a href="table.html">Table</a></li>
                        <li><a href="tabs.html">Tabs</a></li>
                        <li><a href="gallery.html">Gallery</a></li>
                        <li><a href="notif.html">Notifications</a></li>
                        <li><a href="charts.html">Charts</a></li>
                        <li><a href="typo.html">Typography</a></li>
                        <li><a href="icons.html">Icons</a></li>
                        <li><a href="calendar.html">Calendar</a></li>
                    </ul>
                </li>
                <li><a href="#"><img src="/adminimg/icons/menu/brush.png" alt="" /> Another submenu</a>
                    <ul>
                        <li><a href="#">Fake menu #1</a></li>
                        <li><a href="#">Fake menu #2</a></li>
                        <li><a href="#">Fake menu #3</a></li>
                    </ul>
                </li>
                <li><a href="#"><img src="/adminimg/icons/menu/brush.png" alt="" /> Infinite sublevel</a>
                    <ul>
                        <li><a href="#">Fake menu #1</a></li>
                        <li><a href="#">Fake menu #2</a></li>
                        <li><a href="#">Fake menu #3</a>
                            <ul>
                                <li><a href="#">Fake menu #1</a></li>
                                <li><a href="#">Fake menu #2</a></li>
                                <li><a href="#">Fake menu #3</a>
                                    <ul>
                                        <li><a href="#">Fake menu #1</a></li>
                                        <li><a href="#">Fake menu #2</a></li>
                                        <li><a href="#">Fake menu #3</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="nosubmenu"><a href="#"><img src="/adminimg/icons/menu/lab.png" alt="" /> This button is useless</a></li>
                <li class="nosubmenu"><a href="modal.html" class="zoombox w450 h700"><img src="/adminimg/icons/menu/comment.png" alt="" /> Modal box</a></li>
            </ul>
            <a href="#collapse" id="menucollapse">&#9664; Collapse sidebar</a>

        </div>